#!/usr/bin/env python3
# Cockpit generator — rewrites BRIEF.md from state.json + ledgers. Run after
# every chapter sync. 0 chapters is a legal state (pre-chapter-1 brief).
import io, re, glob, os, sys, json
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

st = json.load(io.open('checks/state.json', encoding='utf-8'))
CFG = json.load(io.open('checks/config.json', encoding='utf-8'))
nums = sorted(int(re.findall(r'\d+', f)[0]) for f in glob.glob('chapters/chapter_*.md'))
newest = nums[-1] if nums else 0

# active D-rows
active, held = [], []
if os.path.exists('DIVERGENCE_LEDGER.md'):
    for line in io.open('DIVERGENCE_LEDGER.md', encoding='utf-8'):
        m = re.match(r'^\|\s*(D-\d+|REVEAL-\w+)\s*\|\s*(ACTIVE|HELD|RESOLVED|DORMANT)\s*\|\s*([^|]*)\|', line)
        if m:
            (active if m.group(2) == 'ACTIVE' else held).append(f'{m.group(1)} ({m.group(3).strip()})')

# ore status for the next slot
idx = io.open('canon_extract/SEASON1_INDEX.txt', encoding='utf-8').read()
slot = st.get('canon_slot', 1)
m_slot = re.search(rf'^#\s*{slot:02d}\s*\|\s*\d+\s*\|([^|]+)\|', idx, re.M)
title = m_slot.group(1).strip() if m_slot else '?'
ore_done = re.search(rf'^#\s*{slot:02d}\s*.*ORE DONE', idx, re.M) is not None

bound = st.get('cuff', 'not arrived').upper().startswith('BOUND') if newest == 0 else None
if bound is None and nums:
    rec = st.get(str(newest), {})
    bound = str(rec.get('cuff', '')).upper().startswith('BOUND')

pos = f'position: end of chapter {newest}' if newest else 'position: before chapter 1 (story not started)'
out = f"""# BRIEF.md — the cockpit (auto-generated by checks/brief.py — do not hand-edit)
{pos}
canon: S1 slot {slot} — {title} (production N° {100 + slot}) · ore: {'VERIFIED — file exists' if ore_done else 'PENDING — extract before writing (recipe in SEASON1_INDEX.txt)'}
state: resonance {st['resonance']}/100 · Cuff: {st['cuff']} · Kwami: {st['kwami']} · Evolution: {st['evolution']} · camouflage: {st.get('camouflage', 'latent')}
identity lock: {'LIFTED (cuff BOUND)' if bound else 'ENGAGED — no Chameleon / Versa-Staff / Evolution! / Kamé in prose'}
akumatized so far: {st.get('akumatized_total', 0)} · butterflies shown total: {st.get('butterflies_total', 0)}
OC: {CFG['oc'].get('name', 'TBD')} (names: {CFG['oc'].get('names') or 'TBD — round-2 question pending'})

## Standing laws (never drop from this file)
1. BUTTERFLY LAW — every chapter shows ≥3 butterflies; none is silent.
2. NO FORCED LENGTH — complete naturally; whatever it takes; no floor, no padding.
3. TIGHT AU — canon tracked episode-by-episode (S1 production order); our presence warps from chapter 1.
4. IDENTITY LOCK — until Cuff: BOUND in a footer, the hero name, weapon, ultimate and Kwami name are words that do not exist in prose.
5. REVEAL LOCKS — Hawk Moth's identity, Ladybug's, Cat Noir's: never stated in prose without an ACTIVE REVEAL D-row.
6. TONE — like canon (canon tone, canon humor beats, canon stakes).

## Active D-rows (moving threads)
{chr(10).join('- ' + a for a in active) if active else '- (none active yet)'}

## Held D-rows (planted, not yet moving)
{chr(10).join('- ' + h for h in held) if held else '- (none)'}

## Next actions
1. Extract ore for slot {slot} if pending (SEASON1_INDEX.txt recipe).
2. checks/prewrite_board.py before drafting; checks/run_all.sh after syncing.
3. Footer contract: THE_CODEX.md §FOOTER.
"""
io.open('BRIEF.md', 'w', encoding='utf-8').write(out)
print(f'brief: BRIEF.md written ({pos}; slot {slot} {title})')
