#!/usr/bin/env python3
"""BUILD_CONTINUATION — regenerate CONTINUATION_PROMPT.md from the derived state.

The hand-written version said "end of Chapter 28" while the story was at chapter 61. Generated files
do not rot. Run after every chapter; `verify_stale.py` enforces it.

Usage:
    python3 checks/build_continuation.py
    python3 checks/build_continuation.py --check
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import state as STATE
import ensemble_schedule as ES

OUT = os.path.join(ROOT, "CONTINUATION_PROMPT.md")
MARK_BEGIN = "<!-- GENERATED-BY checks/build_continuation.py — DO NOT HAND-EDIT -->"
MARK_END = "<!-- END GENERATED -->"

# 🔒 These are the standing locks. They move only when a chapter deliberately triggers one.
LOCKS = [
    "the 1,000-year crossing is DONE (ch40, hawk 1,164 at the crossing) — do not re-stage it",
    "Hawk-Soul Union — the trump card; heavy soul-power drain; **first on-page use still reserved**",
    "Shrek named as Wu Zhangkong's origin (canon ch204 is the scheduled reveal, not before)",
    "Na'er's return",
    "Gu Yue's true nature (Silver Dragon King)",
    "battle armor worn",
    "the fusion door opened",
    "the Spirit Pagoda card's contents revealed",
    "who forged the blade",
    "what answered the hawk",
    "who Mu Chen's first was",
    "who has been giving him things",
]


def build():
    st = STATE.derive()
    n = st["latest_chapter"]
    sched = ES.SCHEDULE.get(n, {})
    ens = [sched[k][1] for k in ("wulin", "xiexie", "guyue", "xiaoyan", "yangzi", "jinxi", "weixf")
           if k in sched]

    L = []
    A = L.append
    A("# CONTINUATION PROMPT")
    A("")
    A(MARK_BEGIN)
    A("")
    A("_Generated by `checks/build_continuation.py`. Do not hand-edit. Edit the chapter footers or_")
    A("_`checks/ensemble_schedule.py`, then re-run the generator._")
    A("")
    A(f"## Where the story is: end of Chapter {n}. Next chapter is {n + 1}.")
    A("")
    A("## Read these first, in this order")
    A("")
    A("1. **`LIN_HAO_STATUS.md`** — generated current state + the canon benchmark table.")
    A("2. **`THE_CODEX.md` §THE ADVANTAGE LEDGER** — the fifteen things that are above baseline, and")
    A("   the standing instruction: *when writing Lin Hao, imagine what he is.*")
    A(f"3. **`THE_CODEX.md` §THE REALM GAP LAW** — effective **{st['effective_realm']}** "
      f"({st['effective_rank_band'][0]}–{st['effective_rank_band'][1]}); a lower-realm character")
    A("   defeating him is nonsense; Gu Yue outlasts him, she does not beat him.")
    A("4. **`THE_CODEX.md` §THE FOURTH RING LAW** — ten-thousand-year+ ⇒ BLACK ring; martial soul")
    A("   evolves to TOP-LEVEL; 🔴 **\"Divine Stormbringer\" is CANCELLED**.")
    A("5. **`CHARACTER_STATS.md`** — every canon character number, with its canon citation.")
    A("6. **`PROBLEM_INVENTORY.md`** — what is owed. 🔴 **Read the CURRENT open list, not a name\n   remembered from a previous session.** On 2026-08-29 this generator hard-coded \"F1 is the\n   blocker\" and \"OWED BEFORE ANY COMBAT CHAPTER — F1\" for 22 chapters after F1 had closed\n   in ch40 — and four documents inherited the false claim from it.")
    A("")
    A("## Current state")
    A("")
    # verify.py's SYNC check looks for the literal "rank <N>" and the bare spiritual-power number.
    A(f"- **rank {st['current_rank']} — {st['current_realm']}** · ceiling {st['rank_ceiling']} ({st['rank_ceiling_reason']})")
    A(f"- **Effective combat power: 🔴 {st['effective_realm']} ({st['effective_rank_band'][0]}–{st['effective_rank_band'][1]})**, ceiling {st['effective_realm']} peak")
    A(f"- **{st['rings']['count']} {st['rings']['colour']} rings**, perfectly compatible · spiritual power **{st['current_spiritual_power']}** · hawk **{st['current_hawk_years']:,}**")
    A(f"- **Ledger {st['current_ledger']}** · 🔨 **{st['current_smith_rank']}th rank ({st['current_smith_title']})** · ⚔️ **Sword Intent**")
    A("")
    A("## 🔴 OWED — read from PROBLEM_INVENTORY.md at generation time")
    A("")
    # 🔴 DERIVED, NOT HARDCODED. This block used to hard-code "the purple-ring skill evolution is
    # unwritten" — which had been FALSE for 22 chapters, since F1 closed in ch40. Every document
    # that read this file inherited the lie. If the inventory cannot be parsed, say so loudly
    # rather than falling back to a remembered list.
    owed = read_open_problems()
    if owed is None:
        A("⚠️ **PROBLEM_INVENTORY.md has no OPEN-PROBLEMS block. This generator will not scrape")
        A("the free-text tables — three attempts at that produced three different wrong answers.")
        A("Go and read PROBLEM_INVENTORY.md by hand.**")
    elif not owed:
        A("_The OPEN-PROBLEMS block is empty — nothing is owed._")
    for row in (owed or []):
        A(f"- **{row[0]}** — {row[1]}  \n  _status: {row[2]}_")
    A("")
    A("## Ensemble now")
    A("")
    for e in ens:
        A(f"- {e}")
    A("")
    A("## Locks still held")
    A("")
    for l in LOCKS:
        A(f"- {l}")
    A("")
    A("## Definition of done for the next chapter")
    A("")
    A("```bash")
    import paths as _P
    A(f"cd {_P.PROJECT}")
    A("python3 checks/state.py                 # re-derive state from the footers")
    A("python3 checks/apply_ensemble.py        # rewrite the ensemble block in every footer")
    A("python3 checks/build_status.py          # regenerate LIN_HAO_STATUS.md")
    A("python3 checks/build_continuation.py    # regenerate this file")
    A("sh checks/run_all.sh                    # must exit 0 — thirteen layers")
    A("```")
    A("")
    A("Every number in the new chapter's footer must trace to `CHARACTER_STATS.md` §1 or be labelled AU.")
    A("")
    A(MARK_END)
    return "\n".join(L) + "\n"


def read_open_problems():
    """Read the OPEN-PROBLEMS block from PROBLEM_INVENTORY.md.

    🔴 WHY A BLOCK AND NOT A SCRAPE. This file used to hard-code "F1 — the purple-ring skill
    evolution is unwritten" as the owed item, and it stayed there for 22 chapters after F1
    closed in ch40; four documents inherited the false claim. Replacing the string with a
    scrape of the free-text tables was tried and produced three different wrong answers,
    because the tables mix open and closed rows across ten id series and their cells contain
    literal `|` characters. So the inventory now carries one unambiguous block.
    """
    path = os.path.join(ROOT, "PROBLEM_INVENTORY.md")
    if not os.path.exists(path):
        return None
    t = open(path, encoding="utf-8").read()
    m = _re.search(r"<!--\s*OPEN-PROBLEMS-BEGIN(.*?)OPEN-PROBLEMS-END\s*-->", t, _re.S) \
        if (_re := __import__("re")) else None
    if not m:
        return None
    out = []
    for line in m.group(1).strip().split("\n"):
        parts = [x.strip() for x in line.split("|")]
        if len(parts) == 3 and _re.match(r"^[A-Z]\d{1,2}$", parts[0]):
            out.append(tuple(parts))
    return out


def main():
    text = build()
    if "--check" in sys.argv:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        m = re.search(re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END), cur, re.S)
        new_block = text[text.find(MARK_BEGIN):text.find(MARK_END) + len(MARK_END)]
        if (m.group(0) if m else "") != new_block:
            print("build_continuation: CONTINUATION_PROMPT.md is STALE — run "
                  "`python3 checks/build_continuation.py`")
            sys.exit(1)
        print("build_continuation: CONTINUATION_PROMPT.md is current")
        sys.exit(0)

    old = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    if old and MARK_BEGIN not in old:
        arc = os.path.join(ROOT, "CONTINUATION_PROMPT_ARCHIVE_ch28.md")
        if not os.path.exists(arc):
            open(arc, "w", encoding="utf-8").write(old)
            print(f"build_continuation: old hand-written file archived to {os.path.basename(arc)}")
    open(OUT, "w", encoding="utf-8").write(text)
    st = STATE.derive()
    print(f"build_continuation: CONTINUATION_PROMPT.md regenerated at ch{st['latest_chapter']}")


if __name__ == "__main__":
    main()
