#!/usr/bin/env python3
"""LAYER 5 — STALENESS. A status file that is out of date is worse than none.

THE MEASURED FAILURE (found 2026-08-28, user: "Lin stutas file don't show full current things"):
    LIN_HAO_STATUS.md      said "End of Chapter 18"   while the story was at chapter 61  (43 behind)
    CONTINUATION_PROMPT.md said "end of Chapter 28"   while the story was at chapter 61  (37 behind)
    POWER_MODEL.md         described a rank-30 wall that opened in ch40
    checks/state.py        hardcoded rank_ceiling = 30, which expired at ch40

Every one of those was hand-maintained. Hand-maintained status files rot. So:
  * LIN_HAO_STATUS.md is now GENERATED by checks/build_status.py — this check runs it in --check mode.
  * CONTINUATION_PROMPT.md must name the current chapter.
  * No second copy of any tracked document may exist (they were deleted 2026-08-29).
  * The ensemble schedule must cover every chapter that exists.

Usage:  python3 checks/verify_stale.py
"""
import os, re, sys, glob, subprocess, json

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

errors, warnings = [], []
chapters = sorted(glob.glob(os.path.join(ROOT, "chapters", "chapter_*.md")))
LATEST = max(int(re.search(r"chapter_(\d+)", os.path.basename(p)).group(1)) for p in chapters)

# ---- 1. LIN_HAO_STATUS.md must be generated and current ----
r = subprocess.run([sys.executable, os.path.join(HERE, "build_status.py"), "--check"],
                   capture_output=True, text=True)
if r.returncode != 0:
    errors.append("LIN_HAO_STATUS.md is stale. Run: python3 checks/build_status.py")
else:
    print("  ok   LIN_HAO_STATUS.md is generated and current")

# ---- 2. CONTINUATION_PROMPT.md must name the current chapter ----
cp = os.path.join(ROOT, "CONTINUATION_PROMPT.md")
if os.path.exists(cp):
    t = open(cp, encoding="utf-8").read()
    nums = [int(x) for x in re.findall(r"(?:end of |End of |after |next[:=]?\s*)[Cc]hapter\s*(\d{1,3})", t)]
    nums += [int(x) for x in re.findall(r"\bchapter\s*(\d{1,3})\b", t)]
    if not nums:
        warnings.append("CONTINUATION_PROMPT.md names no chapter number at all")
    else:
        top = max(nums)
        if top < LATEST:
            errors.append(
                f"CONTINUATION_PROMPT.md is stale: its highest chapter reference is {top}, "
                f"the story is at {LATEST}. Update it or replace it with a pointer to the "
                f"generated LIN_HAO_STATUS.md.")
        else:
            print(f"  ok   CONTINUATION_PROMPT.md references ch{top} (story at ch{LATEST})")

# ---- 3. 🔴 NO SECOND COPY MAY EXIST AT ALL (§THE TWO-COPIES LAW) ----
# HISTORY OF THIS CHECK, so nobody "improves" it backwards:
#   v1  Nothing compared the copies. CHARACTER_STATS's reference copy drifted 51 lines behind and
#       RELATIONSHIPS' 14 behind, and the suite stayed green. The second copy silently became a
#       different, older story.
#   v2  We made run_all.sh SYNC the copies and made this check FAIL when they differed. Better —
#       but it institutionalised the liability: five copies, five syncs, every run, forever, and
#       any tool or human that wrote to the copy directly still poisoned it.
#   v3  (2026-08-29, user: "Don't create too many things ... delete extra files") The copies were
#       DELETED. A second copy is not a problem to keep in sync. It is a problem to not have.
#       So the rule is now: these paths must not exist. Recreating one is a failure.
import paths as _P
_REF = os.path.join(_P.CODEX, "reference")
FORBIDDEN_SECOND_COPIES = [
    (os.path.join(_P.CODEX, "05_PROJECT_SOUL_LAND_3.md"),   "THE_CODEX.md"),
    (os.path.join(_REF, "CHARACTER_STATS_SOUL_LAND_3.md"),  "CHARACTER_STATS.md"),
    (os.path.join(_REF, "RELATIONSHIPS_SOUL_LAND_3.md"),    "RELATIONSHIPS.md"),
    (os.path.join(_REF, "CANON_337_600_DOSSIER.md"),        "CANON_337_600_DOSSIER.md"),
    (os.path.join(_REF, "CANON_LEARNING_DOSSIER.md"),       "CANON_LEARNING_DOSSIER.md"),
]
for path, owner in FORBIDDEN_SECOND_COPIES:
    if os.path.exists(path):
        errors.append(
            f"SECOND COPY EXISTS: {path} duplicates {owner}. Delete it — the single source of "
            f"truth is Soul_Land_3_Project/{owner}. If CODEX/ needs to know about it, write a "
            f"one-line POINTER, never a copy.")
    else:
        print(f"  ok   no second copy of {owner}")

# ---- 3c. 🔴 NO "AS-OF" MARKER ANYWHERE MAY BE BEHIND THE STORY ----
# The user's standing instruction is "update everything every time." The failure this enforces is
# the one that keeps recurring: a document that says "END OF CHAPTER 61" while the story is at 62.
# Only the two unambiguous LIVE-STATE forms are matched. Narrative markers ("Gu Yue beat me at
# ch53"), canon chapter numbers ("canon ch 204") and correction notes ("this line previously said
# ch30") are all legitimate and must not be flagged — a check that cries wolf gets ignored.
ASOF = re.compile(r"(?i)\b(?:END OF CHAPTER|CURRENT STATE \(end of chapter|story position at)\s*(\d{1,3})")
DOCS = [os.path.join(ROOT, f) for f in
        ("THE_CODEX.md", "CHARACTER_STATS.md", "RELATIONSHIPS.md", "POWER_MODEL.md",
         "LIN_HAO_PANELS.md", "PROBLEM_INVENTORY.md", "CANON_337_600_DOSSIER.md",
         "CANON_LEARNING_DOSSIER.md", "CANON_ACCESS.md", "SL4_RESEARCH.md")]
DOCS += _P.WORKSPACE_DOCS
# NOT included, each for a named reason:
#   CODEX/01_UNIVERSAL_CODEX.md  — project-agnostic; its worked examples use "Chapter 1 / Chapter 2"
#                                  generically and are not markers for this story.
#   CODEX/97_CLEANUP_LOG.md      — a dated log of past work. "BTTH_Project had no continuation
#                                  prompt as of end of Chapter 11" is history, not live state.
#   CODEX/DECISION_JOURNAL.md    — keyed to the chapter a decision was MADE in.
#   CODEX/CONSEQUENCE_REGISTRY.md— same.
for fp in DOCS:
    if not os.path.exists(fp):
        continue
    txt = open(fp, encoding="utf-8", errors="replace").read()
    for ln, line in enumerate(txt.split("\n"), 1):
        # 🔴 CALIBRATION — three named exemptions, each measured on the first run:
        #   (a) HTML comments carry provenance notes, not live state.
        #   (b) history sections quote the value they are retiring.
        #   (c) CODEX/01_UNIVERSAL_CODEX.md is project-agnostic and writes generic worked
        #       examples ("Lieyang met Huo Yuhao at the end of Chapter 1") that are not
        #       markers for THIS story at all.
        if line.lstrip().startswith("<!--"):
            continue
        if re.search(r"~~|previously said|this line said|was \d+ chapters behind|was \d+ chapters stale|"
                     r"CORRECTED|UPGRADE LOG|CHANGELOG", line, re.I):
            continue
        m = ASOF.search(line)
        # 🔴 CALIBRATION. THE_CODEX.md contains a table of PAST staleness incidents whose
        # "Claimed" column quotes the stale value it is reporting:
        #   | `LIN_HAO_STATUS.md` | "End of Chapter 18" | ch 61 | **43 chapters** |
        # That is evidence, not a live marker. A live as-of marker is prose or a heading; it is
        # never a markdown table cell. Exempt table rows by name rather than dropping the check.
        if m and line.lstrip().startswith("|"):
            continue
        if m and int(m.group(1)) < LATEST:
            errors.append(
                f"{os.path.basename(fp)}:{ln} has a live-state marker for ch{m.group(1)} but the "
                f"story is at ch{LATEST}: \"{m.group(0)}\" — update it")
print("  ok   live-state markers checked across all working documents")

# ---- 3d. 🔴 the OPEN-PROBLEMS block must exist and must match the STILL OPEN table ----
# THE TWO-COPIES LAW applied to the debt list itself. `consequence.py brief` and
# build_continuation.py both read the block; the human-readable table is the other copy. If they
# diverge, one of the two tools lies. Measured 2026-08-29: three attempts to scrape the tables
# produced three different wrong answers, which is why the block exists at all.
pinv = os.path.join(ROOT, "PROBLEM_INVENTORY.md")
if os.path.exists(pinv):
    pt = open(pinv, encoding="utf-8").read()
    mb = re.search(r"<!--\s*OPEN-PROBLEMS-BEGIN(.*?)OPEN-PROBLEMS-END\s*-->", pt, re.S)
    if not mb:
        errors.append("PROBLEM_INVENTORY.md has no OPEN-PROBLEMS block. Both consequence.py brief "
                      "and build_continuation.py read it; without it they cannot report the debt.")
    else:
        block_ids = {m.group(1) for m in
                     re.finditer(r"(?m)^([A-Z]\d{1,2})\s*\|", mb.group(1))}
        # the STILL OPEN table's rows — 🔴 the section, not the whole rest of the file.
        # The first version split on the heading and then scanned EVERYTHING after it, which is
        # the other 60 rows of the inventory (A1-J4, all closed). Bounded at the next heading.
        table_ids = set()
        msec = re.search(r"### 🔴 STILL OPEN.*?\n(?=\n---|\n## )", pt, re.S)
        if msec:
            for line in msec.group(0).split("\n"):
                m = re.match(r"^\|\s*\*\*(~{0,2})([A-Z]\d{1,2})~{0,2}\*\*\s*\|", line)
                # a struck id (~~K1~~) marks a retracted claim, not debt
                if m and not m.group(1) and "---" not in line:
                    table_ids.add(m.group(2))
        if block_ids != table_ids:
            errors.append(
                f"OPEN-PROBLEMS block and the STILL OPEN table disagree. "
                f"block only: {sorted(block_ids - table_ids)} · "
                f"table only: {sorted(table_ids - block_ids)}")
        else:
            print(f"  ok   OPEN-PROBLEMS block matches the STILL OPEN table "
                  f"({len(block_ids)} open: {', '.join(sorted(block_ids))})")

# ---- 4. the ensemble schedule must cover every chapter ----
import ensemble_schedule as ES
missing = [n for n in range(1, LATEST + 1) if n not in ES.SCHEDULE]
if missing:
    errors.append(f"ensemble_schedule.py has no entry for chapter(s): {missing}")
else:
    print(f"  ok   ensemble schedule covers ch1-ch{LATEST}")

# ---- 5. the derived state must agree with the footers (state.json not left stale) ----
sj = os.path.join(HERE, "state.json")
if os.path.exists(sj):
    d = json.load(open(sj, encoding="utf-8"))
    if d.get("latest_chapter") != LATEST:
        errors.append(
            f"checks/state.json says latest_chapter={d.get('latest_chapter')} but the newest "
            f"chapter is {LATEST}. Run: python3 checks/state.py")
    else:
        print(f"  ok   state.json is at ch{LATEST}")

# ---- 6. no file may still carry a superseded rank ceiling ----
for f in ("POWER_MODEL.md", "CONTINUATION_PROMPT.md", "LIN_HAO_STATUS.md"):
    p = os.path.join(ROOT, f)
    if not os.path.exists(p):
        continue
    t = open(p, encoding="utf-8").read()
    if re.search(r"(hard wall|hard-wall|cannot pass|blocked at)[^\n]{0,40}\brank 30\b", t, re.I) \
       and not re.search(r"opened|broke|passed|superseded|was the wall", t, re.I):
        errors.append(
            f"{f} still describes the rank-30 hard wall as current. The third ring was bestowed "
            f"in ch40 and the wall moved to 40.")

# ---- 7. LIN_HAO_PANELS.md — its "current" markers must point at the latest chapter ----
# THE MEASURED FAILURE: the panel said "### Immediate condition (ch 31)" and
# "### Current adaptive priorities" listing "the rank-30 wall — 88 years to the purple crossing"
# while the story was at ch61 and the crossing had happened in ch40. 30 chapters stale.
pan = os.path.join(ROOT, "LIN_HAO_PANELS.md")
if os.path.exists(pan):
    t = open(pan, encoding="utf-8").read()

    # 7a. ANY heading carrying a point-in-time "(ch N)" marker must be the latest chapter.
    # Deliberately format-independent: the first version of this rule required the word "current"
    # in the heading, and a rewrite that dropped that word silently disabled the check. A probe
    # caught it. Match the marker, not the vocabulary.
    for m in re.finditer(r"(?im)^#{2,6}[^\n]*?\(ch\s*(\d{1,3})\)[^\n]*$", t):
        got = int(m.group(1))
        if got < LATEST:
            errors.append(
                f"LIN_HAO_PANELS.md has a point-in-time section marked ch{got} but the story is at "
                f"ch{LATEST}: \"{m.group(0).strip()[:90]}\"")
    # 7a-ii. the same marker inline in a bold "condition" label
    for m in re.finditer(r"(?i)\*\*[^*\n]{0,60}?condition[^*\n]{0,40}?\(ch\s*(\d{1,3})\)", t):
        if int(m.group(1)) < LATEST:
            errors.append(
                f"LIN_HAO_PANELS.md condition marker is ch{m.group(1)} but the story is at ch{LATEST}")

    # 7b. superseded claims presented as live (not struck through, not in a retired list)
    SUPERSEDED = [
        (r"(?<!~~)\bSTALLED AT 30\b",
         "the rank-30 stall ended in ch40 when the third ring was bestowed"),
        (r"(?<!~~)\bHawk-Soul Union\*\* \| \*\*0 — LOCKED\*\*",
         "Union is not merely 'locked' — it upgraded to thousand-year tier at ch40 (F1)"),
        (r"(?m)^\s*3\.\s*\*\*The rank-30 wall\*\* — nothing can be done",
         "the rank-30 wall opened in ch40; the ceiling is now 40"),
        (r"(?<!~~)\b88 years to the purple crossing\b",
         "the purple crossing happened in ch40 (hawk 1,164 at the crossing)"),
    ]
    for rx, why in SUPERSEDED:
        if re.search(rx, t):
            errors.append(f"LIN_HAO_PANELS.md presents a superseded state as current — {why}")

    # 7c. it must carry the two-axis rule and the effective-power line
    if "THOUSAND-YEAR" not in t:
        errors.append("LIN_HAO_PANELS.md does not record the ring TIER of the soul skills. "
                      "Mastery layer and ring tier are separate axes (F1).")
    if "SOUL KING" not in t.upper():
        errors.append("LIN_HAO_PANELS.md does not record his effective combat power (Soul King).")
    print("  ok   LIN_HAO_PANELS.md checked for staleness")

# ---- 8. THE_CODEX.md — no "CURRENT STATE (end of ch N)" marker may be behind ----
# THE_CODEX.md is hand-maintained (canon citations are not derivable), so it rots the same way.
# Found by hand on 2026-08-28: "CURRENT STATE (end of ch 49)", "Current age 885" (true: 1,399),
# "Current (end ch 25)". The UPGRADE LOG is history and is excluded.
codex = os.path.join(ROOT, "THE_CODEX.md")
if os.path.exists(codex):
    ct = open(codex, encoding="utf-8").read()
    body = ct.split("## ⚡ UPGRADE LOG")[0] if "## ⚡ UPGRADE LOG" in ct else ct
    for m in re.finditer(r"(?i)\b(?:CURRENT STATE|Current)\s*\(\s*end(?:\s+of)?\s+ch(?:apter)?\.?\s*(\d{1,3})\s*\)", body):
        got = int(m.group(1))
        if got < LATEST:
            errors.append(
                f"THE_CODEX.md has a current-state marker for ch{got} but the story is at ch{LATEST}: "
                f"\"{m.group(0)}\". Update it, or replace it with a pointer to the GENERATED "
                f"LIN_HAO_STATUS.md.")
    # the hawk age is the single most-quoted live number; it must not be left behind
    hm = re.findall(r"Current age \*\*(\d[\d,]*)\*\*", body)
    if hm:
        import json as _json
        sj = os.path.join(HERE, "state.json")
        if os.path.exists(sj):
            true_hawk = _json.load(open(sj, encoding="utf-8")).get("current_hawk_years")
            for raw in hm:
                if int(raw.replace(",", "")) != true_hawk:
                    errors.append(
                        f"THE_CODEX.md says \"Current age {raw}\" but the hawk is {true_hawk} "
                        f"(ch{LATEST}).")
    print("  ok   THE_CODEX.md current-state markers checked")

# ---- 9. "CURRENT" markers must not state an out-of-date rank ----
# A codex block beginning "CURRENT — Soul Grandmaster rank 30, AT THE HARD WALL" sat undetected for
# 21 chapters after the wall opened at ch40 and the rank reached 36. A block that says CURRENT is the
# most dangerous kind of stale text, because everything else in the file defers to it.
import json as _json
_sj = os.path.join(HERE, "state.json")
_cur_rank = None
if os.path.exists(_sj):
    _cur_rank = _json.load(open(_sj, encoding="utf-8")).get("current_rank")
if _cur_rank:
    for doc in ("THE_CODEX.md", "LIN_HAO_PANELS.md", "POWER_MODEL.md", "CHARACTER_STATS.md",
                "CANON_ACCESS.md", "RELATIONSHIPS.md"):
        fp = os.path.join(ROOT, doc)
        if not os.path.exists(fp):
            continue
        txt = open(fp, encoding="utf-8", errors="replace").read()
        i = txt.find("## 🔄 UPGRADE LOG")
        if i > 0:
            txt = txt[:i]          # the log is history and may quote any old value
        # 🔴 Judge the WHOLE LINE, not a window around the word CURRENT. A correction note reads
        # 'This line previously said "rank 30, AT THE HARD WALL"... Current: rank 36' — a window taken
        # from before the word CURRENT cuts the word "previously" off the front and the filter cannot
        # see it, so a correct correction gets flagged as stale.
        for ln, line in enumerate(txt.split("\n"), 1):
            if not re.search(r"\bCURRENT\b", line, re.I):
                continue
            if re.search(r"→|curve|CORRECTED|previously|next gate|rank 40|this line said|previously said",
                         line, re.I):
                continue
            rm = re.search(r"\brank (\d{1,3})\b", line)
            if rm and int(rm.group(1)) != _cur_rank:
                errors.append(
                    f"{doc}:{ln}: a CURRENT block states rank {rm.group(1)} but the story is at rank "
                    f"{_cur_rank}.\n      {line.strip()[:150]}")

print(f"verify_stale: story at ch{LATEST}")
for w in warnings:
    print("  WARN " + w)
for e in errors:
    print("  FAIL " + e)
if errors:
    print(f"\nverify_stale: {len(errors)} failure(s), {len(warnings)} warning(s)")
    sys.exit(1)
print(f"verify_stale: PASS ({len(warnings)} warning(s))")
sys.exit(0)
